# --------
# 1. Builder
# --------
FROM node:22-alpine AS builder

WORKDIR /app

# Install dependencies using cached layer
COPY package*.json ./
RUN npm ci

# Declare the argument that expect to receive at build time
ARG NEXT_PUBLIC_APP_ENV
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_PUBLIC_ASSETS
ARG NEXT_PUBLIC_GISCUS_REPO
ARG NEXT_PUBLIC_GISCUS_REPO_ID
ARG NEXT_PUBLIC_GISCUS_CATEGORY
ARG NEXT_PUBLIC_GISCUS_CATEGORY_ID
ARG NEXT_PUBLIC_GISCUS_MAPPING
ARG NEXT_PUBLIC_GISCUS_TERM
ARG NEXT_PUBLIC_UMAMI_DATA_WEBSITE_ID
ARG NEXT_PUBLIC_GA_MEASUREMENT_ID
ARG NEXT_PUBLIC_POSTHOG_KEY
ARG NEXT_PUBLIC_POSTHOG_HOST
 
# Set is as an environment variable so the build can access it
ENV NEXT_PUBLIC_APP_ENV=$NEXT_PUBLIC_APP_ENV
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_PUBLIC_ASSETS=$NEXT_PUBLIC_PUBLIC_ASSETS
ENV NEXT_PUBLIC_GISCUS_REPO=$NEXT_PUBLIC_GISCUS_REPO
ENV NEXT_PUBLIC_GISCUS_REPO_ID=$NEXT_PUBLIC_GISCUS_REPO_ID
ENV NEXT_PUBLIC_GISCUS_CATEGORY=$NEXT_PUBLIC_GISCUS_CATEGORY
ENV NEXT_PUBLIC_GISCUS_CATEGORY_ID=$NEXT_PUBLIC_GISCUS_CATEGORY_ID
ENV NEXT_PUBLIC_GISCUS_MAPPING=$NEXT_PUBLIC_GISCUS_MAPPING
ENV NEXT_PUBLIC_GISCUS_TERM=$NEXT_PUBLIC_GISCUS_TERM
ENV NEXT_PUBLIC_UMAMI_DATA_WEBSITE_ID=$NEXT_PUBLIC_UMAMI_DATA_WEBSITE_ID
ENV NEXT_PUBLIC_GA_MEASUREMENT_ID=$NEXT_PUBLIC_GA_MEASUREMENT_ID
ENV NEXT_PUBLIC_POSTHOG_KEY=$NEXT_PUBLIC_POSTHOG_KEY
ENV NEXT_PUBLIC_POSTHOG_HOST=$NEXT_PUBLIC_POSTHOG_HOST

# Copy all source
COPY . .

# Build Next.js
RUN npm run build


# --------
# 2. Runner
# --------
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000
CMD ["node", "server.js"]
